---
apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: "https://github.com/dmuiX/argocd.k8sdev.cloud.git"
  username: dmuiX
  password: "YOUR_GITHUB_TOKEN_HERE" 